Remove redundant class attributes declarations
group-project-gut/lynx-runtime pull request #13
Opened 2023-01-19 19:55 UTC by alpinus4

There are many redundant class attributes declarations that are inherited anyways. 
It greatly clutters the code and makes it less readable.

2023-01-19 22:08 UTC, filip-szweda requested changes

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/action.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/attacks/slash.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/deal_dmg.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/destroy.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/idle.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/move.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/nearby_objects.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/next_scene.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/use.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/wait_for_code.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/actions/wave.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/agent.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/floor.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/interactive_object.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/npcs/enemies/training_dummy.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/object.py
> -    properties: Properties
Remove `Properties` import.

2023-01-19 22:08 UTC, filip-szweda commented on src/objects/portal.py
> -    properties: Properties
Remove `Properties` import.

2023-01-20 06:54 UTC, blazej-smorawski approved these changes

2023-01-20 07:38 UTC, Krystian030 approved these changes

2023-01-22 20:33 UTC, merged